MAKING_VIDEO_WITH_DETECTION = False
MAKING_PHOTO_WITH_DETECTION = False
MAKING_PHOTO_WITHOUT_DETECTION = False
INCLUDING_ALL_PHOTOS = True

MINIMAL_DETECTION = 0.95
MAXIMAL_COMPARE = 0.60
MINIMAL_MID_SQR_ERR = 4500

COUNT_OF_VIDEO_PARTS = 15
COUNT_OF_TOP_PHOTOS = 5
EXTRA_FRAMES_MULTIPLY = 2
