MAKING_VIDEO_WITH_DETECTION = False
MAKING_PHOTO_WITH_DETECTION = False
MAKING_PHOTO_WITHOUT_DETECTION = False
INCLUDING_ALL_PHOTOS = True

MINIMAL_DETECTION = 0.95
MAXIMAL_COMPARE = 0.65
MINIMAL_MID_SQR_ERR = 3500

COUNT_OF_VIDEO_PARTS = 30
COUNT_OF_TOP_PHOTOS = 5
